name    'chmac-security_update_notifier'
version '0.0.5'
source 'UNKNOWN'
author 'chmac'
license 'UNKNOWN'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
